### ISSUE TITLE
Improve code stability by wrapping codes that query API with retry functions

### ISSUE THREAD

**Issue by 2320sharon** [SatelliteShorelines/coastsat_package#7]
Add a retry wrapper to `im_bands = image_ee.getInfo()["bands"]` which gets the bands available in the image by querying the Google Earth engine API. In the event that the connection cannot be made this code should not throw an error until it has attempted to query the API at least three times. This should make downloads more stable.

**Comment by 2320sharon** [comment]
This function has the potential to enter an infinite loop if a connection cannot be made with GEE to get the info for the image. This is because `.getInfo()` in the line `im_list = col.getInfo().get("features"` within this function queries the GEE API and if it cannot establish a connection it throws an error wich this loop catches then attempts to connection again, this process goes on infinitely if a connection to GEE cannot be established. I want to refactor this code to not have an infinite loop and to instead attempt to reconnect 3 times using the retry wrapper, then throw an error if a connection cannot be made

```
@retry
def get_image_info(collection, satname, polygon, dates, **kwargs):
    """
    Reads info about EE images for the specified collection, satellite and dates

    KV WRL 2022

    Arguments:
    -----------
    collection: str
        name of the collection (e.g. 'LANDSAT/LC08/C02/T1_TOA')
    satname: str
        name of the satellite mission
    polygon: list
        coordinates of the polygon in lat/lon
    dates: list of str
        start and end dates (e.g. '2022-01-01')

    Returns:
    -----------
    im_list: list of ee.Image objects
        list with the info for the images
    """
    while True:
        try:
            # get info about images
            ee_col = ee.ImageCollection(collection)
            # Initialize the collection with filterBounds and filterDate
            col = ee_col.filterBounds(ee.Geometry.Polygon(polygon)).filterDate(
                dates[0], dates[1]
            )
            # If "S2tile" key is in kwargs and its associated value is truthy (not an empty string, None, etc.),
            # then apply an additional filter to the collection.
            if kwargs.get("S2tile"):
                col = col.filterMetadata(
                    "MGRS_TILE", "equals", kwargs["S2tile"]
                )  # 58GGP
                print(f"Only keeping user-defined S2tile: {kwargs['S2tile']}")
            im_list = col.getInfo().get("features")
            break
        except:
            continue
    # remove very cloudy images (>95% cloud cover)
    im_list = remove_cloudy_images(im_list, satname)
    return im_list

```

**Comment by 2320sharon** [comment]
This function solves the infinite Loop problem by removing the while true Loop and wrapping the function with the retry wrapper. I also implemented a small script to test this functionality called `test_check_images_available.py`

The new behavior of this function is that it attempts to retry the connection three times and if it fails it raises an exception, but if it can it does attempt to reconnect and get the number of available images.

In the event a connection cannot be made an exception is raised telling the user 3 attempts were made to download, but all failed
```

@retry  # Apply the retry decorator to the function
def get_image_info(collection, satname, polygon, dates, **kwargs):
    """
    Reads info about EE images for the specified collection, satellite, and dates

    KV WRL 2022

    Arguments:
    -----------
    collection: str
        name of the collection (e.g. 'LANDSAT/LC08/C02/T1_TOA')
    satname: str
        name of the satellite mission
    polygon: list
        coordinates of the polygon in lat/lon
    dates: list of str
        start and end dates (e.g. '2022-01-01')

    Returns:
    -----------
    im_list: list of ee.Image objects
        list with the info for the images
    """
    # get info about images
    ee_col = ee.ImageCollection(collection)
    # Initialize the collection with filterBounds and filterDate
    col = ee_col.filterBounds(ee.Geometry.Polygon(polygon)).filterDate(
        dates[0], dates[1]
    )
    # If "S2tile" key is in kwargs and its associated value is truthy (not an empty string, None, etc.),
    # then apply an additional filter to the collection.
    if kwargs.get("S2tile"):
        col = col.filterMetadata("MGRS_TILE", "equals", kwargs["S2tile"])  # 58GGP
        print(f"Only keeping user-defined S2tile: {kwargs['S2tile']}")
    im_list = col.getInfo().get("features")
    # remove very cloudy images (>95% cloud cover)
    im_list = remove_cloudy_images(im_list, satname)
    return im_list

```
## Sample Output

The following code shows the output of a call to `SDS_download.check_images_available(inputs)` which calls `get_image_info` multiple times. In this scenario, the internet connection fails when `get_image_info` is called to get the images available in tier one. The result of there being no internet connection causes the message to print that three attempts failed to download and it halts all downloads instead of looping forever
```
Number of images available between 2014-04-29 and 2014-06-01:
- In Landsat Tier 1 & Sentinel-2 Level-1C:
Attempt 1 failed: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

Attempt 2 failed: HTTPSConnectionPool(host='earthengine.googleapis.com', port=443): Max retries exceeded with url: /v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022935F964A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Attempt 3 failed: HTTPSConnectionPool(host='earthengine.googleapis.com', port=443): Max retries exceeded with url: /v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002293604C2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000002293604C2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='earthengine.googleapis.com', port=443): Max retries exceeded with url: /v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002293604C2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\development\doodleverse\coastsat_package\coastsat_package\src\coastsat\SDS_download.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "C:\development\doodleverse\coastsat_package\coastsat_package\src\coastsat\SDS_download.py", line 1265, in get_image_info
    im_list = col.getInfo().get("features")
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\ee\collection.py", line 133, in getInfo
    return super(Collection, self).getInfo()
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\ee\computedobject.py", line 96, in getInfo
    return data.computeValue(self)
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\ee\data.py", line 955, in computeValue
    return _execute_cloud_call(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\ee\data.py", line 346, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper      
    return wrapped(*args, **kwargs)
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\googleapiclient\http.py", line 923, in execute
    resp, content = _retry_request(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\googleapiclient\http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\ee\_cloud_api_utils.py", line 65, in request
    response = session.request(
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\sf230\anaconda3\envs\coastsat_package_dev\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='earthengine.googleapis.com', port=443): Max retries exceeded with url: /v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002293604C2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\development\doodleverse\coastsat_package\coastsat_package\test_check_images_available.py", line 79, in <module>
    SDS_download.check_images_available(inputs)
  File "C:\development\doodleverse\coastsat_package\coastsat_package\src\coastsat\SDS_download.py", line 1060, in check_images_available        
    im_list = get_image_info(
  File "C:\development\doodleverse\coastsat_package\coastsat_package\src\coastsat\SDS_download.py", line 143, in wrapper
    sleep_or_exception(image_id, i, max_tries, e)
  File "C:\development\doodleverse\coastsat_package\coastsat_package\src\coastsat\SDS_download.py", line 111, in sleep_or_exception
    raise TooManyRequests(
coastsat.SDS_download.TooManyRequests: Failed to download after 3 attempts : Unknown image id
```
